spring:
  application:
    name: hammer-internal
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bear}
    username: ${DB_USERNAME:hobom}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    schemas:
      - auction
      - hammer
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8090}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: hammer-internal
    version: 0.0.1-SNAPSHOT
